"""empty message

Revision ID: fbd86f6bafc7
Revises: 
Create Date: 2019-04-23 15:10:40.261756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbd86f6bafc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Main_bar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('New_download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('forums_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=150), nullable=True),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producttitle', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('title_id'),
    sa.UniqueConstraint('title_id')
    )
    op.create_table('topic',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('title_id'),
    sa.UniqueConstraint('title_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('Download_Bar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=False),
    sa.Column('MainID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MainID'], ['Main_bar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('cluster_download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('MainID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MainID'], ['New_download.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('customer_logo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('urlForimage', sa.String(length=140), nullable=True),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('indexID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indexID'], ['index_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_bar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=False),
    sa.Column('MainID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MainID'], ['Main_bar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('dz_bar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=False),
    sa.Column('MainID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MainID'], ['Main_bar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('enterprise_download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('MainID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MainID'], ['New_download.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('forums_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=180), nullable=True),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['forums_topic.id'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('my_sql_bar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=False),
    sa.Column('MainID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MainID'], ['Main_bar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('my_sql_community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('com_link', sa.String(length=200), nullable=False),
    sa.Column('MainID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MainID'], ['New_download.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('product__cluster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('indexID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indexID'], ['index_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product__enterprise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('indexID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indexID'], ['index_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product__sql_clound',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('indexID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indexID'], ['index_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_forOME',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('indexID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['indexID'], ['index_product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_my_sqlndb_cluster',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['product.title_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('product_mysql_server',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['product.title_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('product_x_devAPI',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['product.title_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('topicHA__scalability',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['topic.title_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('topic_administrator__guides',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['topic.title_id'], ),
    sa.PrimaryKeyConstraint('doc_id'),
    sa.UniqueConstraint('doc_id')
    )
    op.create_table('topic_general',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['title_id'], ['topic.title_id'], ),
    sa.PrimaryKeyConstraint('doc_id'),
    sa.UniqueConstraint('doc_id')
    )
    op.create_table('windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('win_link', sa.String(length=200), nullable=False),
    sa.Column('MainID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MainID'], ['New_download.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('forums_post_contect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contect', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('writer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['forums_post.id'], ),
    sa.ForeignKeyConstraint(['writer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forums_post_contect_timestamp'), 'forums_post_contect', ['timestamp'], unique=False)
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('MainID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['MainID'], ['Download_Bar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language')
    op.drop_index(op.f('ix_forums_post_contect_timestamp'), table_name='forums_post_contect')
    op.drop_table('forums_post_contect')
    op.drop_table('windows')
    op.drop_table('topic_general')
    op.drop_table('topic_administrator__guides')
    op.drop_table('topicHA__scalability')
    op.drop_table('product_x_devAPI')
    op.drop_table('product_mysql_server')
    op.drop_table('product_my_sqlndb_cluster')
    op.drop_table('product_forOME')
    op.drop_table('product__sql_clound')
    op.drop_table('product__enterprise')
    op.drop_table('product__cluster')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('my_sql_community')
    op.drop_table('my_sql_bar')
    op.drop_table('forums_post')
    op.drop_table('followers')
    op.drop_table('enterprise_download')
    op.drop_table('dz_bar')
    op.drop_table('document_bar')
    op.drop_table('customer_logo')
    op.drop_table('cluster_download')
    op.drop_table('Download_Bar')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('topic')
    op.drop_table('product')
    op.drop_table('index_product')
    op.drop_table('forums_topic')
    op.drop_table('New_download')
    op.drop_table('Main_bar')
    # ### end Alembic commands ###
