"""empty message

Revision ID: ff7bb2c0639d
Revises: 
Create Date: 2019-04-19 23:43:26.913499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff7bb2c0639d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mainbar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('title_id')
    )
    op.create_table('topic',
    sa.Column('title_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('title_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('cluster_download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('MainID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['MainID'], ['mainbar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprise_download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('MainID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['MainID'], ['mainbar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('my_sql_community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('com_link', sa.String(length=200), nullable=True),
    sa.Column('MainID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['MainID'], ['mainbar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('product_my_sqlndb_cluster',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['product.title_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('product_mysql_server',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['product.title_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('product_x_devAPI',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['product.title_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('title',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('MainID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['MainID'], ['mainbar.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('topicHA__scalability',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['topic.title_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('topic_administrator__guides',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['topic.title_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('topic_general',
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=140), nullable=True),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['title_id'], ['topic.title_id'], ),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_table('windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('win_link', sa.String(length=200), nullable=True),
    sa.Column('MainID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['MainID'], ['mainbar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('windows')
    op.drop_table('topic_general')
    op.drop_table('topic_administrator__guides')
    op.drop_table('topicHA__scalability')
    op.drop_table('title')
    op.drop_table('product_x_devAPI')
    op.drop_table('product_mysql_server')
    op.drop_table('product_my_sqlndb_cluster')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('my_sql_community')
    op.drop_table('followers')
    op.drop_table('enterprise_download')
    op.drop_table('cluster_download')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('topic')
    op.drop_table('product')
    op.drop_table('mainbar')
    op.drop_table('language')
    # ### end Alembic commands ###
